### ISSUE TITLE
Fails installing and can't start

### ISSUE THREAD

**Issue by TheRedMajora** [hearthmod/hearthmod#1]
Here are some of the errors I get:

During Installation:
```
cd script/mechanics/ && python main.py
Traceback (most recent call last):
   File "main.py", line 19, in <module>
      from couchbase.bucket import Bucket
ImportError: No module named couchbase.bucket
make: *** [script] Error 1
```

During Start:
```
valgrind: ./hm_gameserver/hm_gameserver: No such file or directory
spawn-fcgi: child exited with: 1
```

**Comment by farb3yonddriv3n** [comment]
Hi did you follow the installation instructions in readme file? What os are you using?

**Comment by TheRedMajora** [comment]
The github project readme? If so, yes.
Did ‘git clone https://github.com/hearthmod/hearthmod.git’ then ‘cd hearthmod’ and ‘bash host_ctl_ubuntu.sh uninstalled’

I am running Ubuntu 14.4.2 through VirtualBox 5.2.6

**Comment by farb3yonddriv3n** [comment]
Try 16.04 please that's the one I tested it with, otherwise you'd need to figure out package names or actuallly compile the library you're missing

**Comment by TheRedMajora** [comment]
Tried 16.4, but I still have the same issue.

This time I managed to find another error during installation which might shed more light on the situation:
```

  Running setup.py install for couchbase ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_Kn4LK/couchbase/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-z4AjFQ-record/install-record.txt --single-version-externally-managed --compile:

```

**Comment by farb3yonddriv3n** [comment]
Sorry for a late answer. That is issue with python couchbase module which is something beyond us. Please try to install it manually and then re-run the entire process. Basically what you want is that when in python shell and you write ' import couchbase ' that it doesn't fail. There is also hearthmod installation video guide https://www.youtube.com/watch?v=gq7h9zRmrHs , where there is no such issue; so perhaps try to watch that.

**Comment by n4ru** [comment]
After installing a bunch of external dependencies, I'm still getting ``` fatal error: libcouchbase/views.h: No such file
compilation terminated.```
 after running through the setup process, and installing couchbase beforehand doesn't seem to fix it.
