### ISSUE TITLE
Problem while starting Hearthmod

### ISSUE THREAD

**Issue by sk996** [hearthmod/hearthmod#2]
I've got this problem starting Hearthmod:

```
Starting hearthmod
valgrind: ./hm_gameserver/hm_gameserver: No such file or directory
./hm_lobbyserver/hm_lobbyserver: error while loading shared libraries: libcouchbase.so.2: cannot open shared object file: No such file or directory
{core} Note: no DH parameters found in ./hm_stud/cert/test.com.pem
{core} Daemonized as pid 8469.
spawn-fcgi: child exited with: 1
```

What does it mean?   

I used Ubuntu 16.04.2  64bit   and  Oracle Virtual Box Manager  5.2.22. 
I've watched your installation guide video on you tube (a 42 minutes video).

In the attached text-file, you can find the installation log generated by `bash host_ctl_ubuntu.sh uninstalled &> output`

[Installation log.txt](https://github.com/hearthmod/hearthmod/files/2746199/Installation.log.txt)

What could be the problem?
Thanks for your answers.

Ps. sorry for my bad english, i'm italian.

**Comment by farb3yonddriv3n** [comment]
according to the log, there is a missing python module

ImportError: No module named couchbase.bucket

Try to install it manually and run it again.
